### ISSUE TITLE
Can't create a diagram with a Docker image

### ISSUE THREAD

**Issue by KMax** [LUMII-Syslab/viziquer#2]
- I run the app as described [here](https://github.com/LUMII-Syslab/viziquer#to-run-viziquer-within-a-docker-environment-on-macos-or-linux), 
- opened the `localhost`, signed up and logged in,
- created and opened a project.

And at this point, I don't see how I should create a diagram. Is it a bug or am I missing something?

Browsers: Firefox 68.0.2 and Google Chrome 76.0.3809.132

**Comment by karlisc** [comment]
Could you please post the screen shot of what you have, or sent it to viziquer@lumii.lv

**Comment by KMax** [comment]
Attaching two screenshots...

The project list page:
![Screenshot_2019-09-02 Screenshot](https://user-images.githubusercontent.com/189642/64113799-ece79f80-cd93-11e9-9306-d0c194d03a51.png)

The diagrams page:
![Screenshot_2019-09-02 Screenshot_1](https://user-images.githubusercontent.com/189642/64113798-ece79f80-cd93-11e9-875e-829fa9a174a9.png)

**Comment by karlisc** [comment]
Do you have a tool configuration in place, if you log as an administrator?

**Comment by KMax** [comment]
I don't think so, because I tried to follow the [instructions](https://github.com/LUMII-Syslab/viziquer#configuration-for-the-first-use), but I don't see the Configurator page.

**Comment by karlisc** [comment]
Are you the first user logging into the instance?
Which operating system you are deploying the image on?

**Comment by KMax** [comment]
Yes, I'm the first user. I'm using Linux.

I just stopped, removed the data folder where MongoDB stores its data and recreated the containers. And after that, I can see the Configurator page.

Now it works, I don't know what was the issue. @karlisc Thanks anyway!

**Comment by karlisc** [comment]
Good Luck! 
If you are at [Semantics 2019](https://2019.semantics.cc/) conference, I shall do a demo there, may be we can talk.
